# Generated by Django 5.2.2 on 2025-06-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stars', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='customer_images/')),
                ('profession', models.CharField(choices=[('Sales Manager', 'Sales Manager'), ('Tech Leader', 'Technical Leader'), ('DevOps', 'DevOps'), ('Product Manager', 'Product Manager')], default='DevOps', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(default=0)),
                ('level', models.CharField(choices=[('Junior', 'Junior'), ('Middle', 'Mid-Level'), ('Senior', 'Senior')], default='Junior', max_length=20)),
                ('job_type', models.CharField(choices=[('Full time', 'Tam ştat'), ('Part time', 'Yarim ştat'), ('Freelance', 'Frilanser')], default='Full time', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Jobdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_title', models.CharField(max_length=100)),
                ('main_title', models.CharField(max_length=100)),
                ('main_content', models.TextField()),
                ('role_title', models.CharField(max_length=100)),
                ('role_content', models.TextField()),
                ('requirement_title', models.CharField(max_length=100)),
                ('requirement_content', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(default=0)),
                ('level', models.CharField(choices=[('Junior', 'Junior'), ('Middle', 'Mid-Level'), ('Senior', 'Senior')], default='Junior', max_length=20)),
                ('job_type', models.CharField(choices=[('Full time', 'Tam ştat'), ('Part time', 'Yarim ştat'), ('Freelance', 'Frilanser')], default='Full time', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recent_jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='job_images/')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(default=0)),
                ('level', models.CharField(choices=[('Junior', 'Junior'), ('Middle', 'Mid-Level'), ('Senior', 'Senior')], default='Junior', max_length=20)),
                ('job_type', models.CharField(choices=[('Full time', 'Tam ştat'), ('Part time', 'Yarim ştat'), ('Freelance', 'Frilanser')], default='Full time', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=200)),
                ('banner_content', models.TextField()),
                ('banner_image', models.ImageField(upload_to='setting_images/')),
                ('category_title', models.CharField(max_length=100)),
                ('category_icon', models.CharField(max_length=100)),
                ('introduction_title', models.CharField(max_length=100)),
                ('introduction_content', models.TextField()),
                ('introduction_image', models.ImageField(upload_to='category_images/')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('job_content', models.TextField()),
                ('job2_title', models.CharField(max_length=100)),
                ('job2_content', models.TextField()),
                ('users', models.IntegerField(default=0)),
                ('jobs', models.IntegerField(default=0)),
                ('video', models.FileField(upload_to='setting_files/')),
                ('recent_title', models.CharField(max_length=100)),
                ('recent_content', models.TextField()),
                ('customer_title', models.CharField(max_length=100)),
                ('over_title', models.CharField(max_length=100)),
                ('over_content', models.TextField()),
                ('about_title', models.CharField(max_length=100)),
                ('service_title', models.CharField(max_length=100)),
                ('job_detail', models.CharField(max_length=100)),
                ('similar_title', models.CharField(max_length=100)),
                ('similar_text', models.TextField()),
                ('contact_title', models.CharField(max_length=100)),
                ('message_title', models.CharField(max_length=100)),
            ],
        ),
    ]
